src/app/services/ui/ui.interaction.service.ts, src/app/view/editor-main-view/data-views/connections.view.ts, src/app/view/editor-main-view/data-views/editor.view.ts, src/app/view/editor-main-view/data-views/nodes.view.ts, src/app/view/editor-main-view/data-views/trainrunsections.view.ts, src/app/view/editor-main-view/data-views/transitions.view.ts, src/app/view/editor-tools-view-component/editor-tools-view.component.ts, src/app/view/util/svg.mouse.controller.ts
Viewport culling is a technique used in computer graphics to improve rendering performance by only rendering objects that are visible within the viewport or rendering area of the screen.
When rendering the Netzgrafik (scene), the current implementation of the SVG graphics engine determines which objects are visible and should be rendered on the screen. This process involves checking whether each object's bounding volume (such as a bounding box or bounding sphere) intersects with the viewport or falls entirely outside of it.
Objects that are completely outside the viewport are considered to be occluded or not visible, so they are not rendered, saving computational resources. On the other hand, objects that intersect with the viewport or partially fall inside it are considered to be visible …
=> rendering - frustum culling implemented  

src/app/streckengrafik/services/sg-6-track.service.ts, src/app/streckengrafik/services/streckengrafik.services.spec.ts
The problem has been fixed. The problem was the wrong band limiter checking against "less than" instead of "less than or equal to". To increase accuracy - 4 second grid resolution. Performance is still ok. In general scheduling only 60s (1min) is scheduled in current scenarios => so 4s is still ok.
=> issue fixed and resolution increase - speed drops but still ok

src/app/app.component.ts, src/app/models/operation.model.ts, src/app/services/data/trainrun.service.ts, src/app/services/data/trainrunsection.service.ts
This is the second part of https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/pull/158, cleaned up and rebased.
Add inputs and outputs so that a custom element user can interact with NGE.
A netzgrafikDto input is introduced to get/set the data service's current DTO. A operation output is introduced to notify about DTO changes. The changes are described by a new Operation class.
The new additions have no impact on the existing behavior and can simply be ignored when unused (e.g. when NGE runs with its own backend).
cc @louisgreiner
=> feat: add AppComponent inputs/outputs

.github/workflows/continuous-integration.yml, .github/workflows/release.yml, package.json
This is the last part of https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/pull/158.
Add two new CI tasks: one to build the standalone variant on push, and another one to publish an NPM package on release.
The latter requires setting up a `NPM_TOKEN` secret in the GitHub repository settings.
All dependencies are removed before publication because the published package is completely standalone: all of the dependencies are bundled in `dist/`.
Add the "repository" field in package.json: it's a requirement for the `npm publish --provenance` flag.
=> feat: publish package on NPM

src/index.html
The automatic dark variant is broken.
Closes: https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/issues/156
=> fix: use light theme for sbb-esta

src/app/models/trainrunsection.model.ts, src/app/services/util/trainrunsection.validator.ts, src/app/utils/math.ts
Use the formula `abs(a - b) < epsilon` to check whether two floating-point values are equal.
=> Use epsilon comparison instead of rounding

src/app/view/editor-properties-view-component/editor-properties-view.component.html
Fix the issue described in:
https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/pull/173#issuecomment-2250557562
Use the vertical-align CSS property instead of manually hardcoding pixel offsets and margins.
=> fix: align theme color picker with buttons

src/app/services/data/node.service.ts, src/app/services/data/note.service.ts, src/app/services/data/trainrun.service.ts, src/app/view/dialogs/note-dialog/note-filter-tab/note-filter-tab.component.ts, src/app/view/dialogs/trainrun-and-section-dialog/trainrun-filter-tab/trainrun-filter-tab.component.ts, src/app/view/editor-side-view/editor-node-detail-view/editor-node-detail-view.component.ts
When using (create, delete, focusout) the trainrun label area, the trainrun label service makes unnecessary calls.
This feature:
- test uniqueness of `labels` before calling `setLabels()`
- remove double calls when `create` a label, but also `focusout` at the same time, thus calling twice the functions
Update:  does the same refactor for node filters
=> refacto trainrun filter service for label uniqueness

src/app/app.component.html, src/environments/environment.model.ts, src/environments/environment.standalone.ts
According to the [sbb-angular docs][1], the sbb-header-environment component should be disabled in production. Do so in standalone mode.
Without this, a ribbon with a "standalone" text is displayed in the top-left corner.
[1]: https://github.com/sbb-design-systems/sbb-angular/blob/main/src/angular/header-lean/header-lean.md#environment
=> fix: disable environment header in standalone mode

src/app/view/editor-side-view/editor-node-detail-view/editor-node-detail-view.component.html, src/app/view/editor-side-view/editor-node-detail-view/editor-node-detail-view.component.ts
Fixes a few issues:
- "keyup" is not triggered when copy-pasting. So if the user right clicks and pastes a new value, the name would not get updated.
- "keyup" triggers each time a character is typed in the input field. This results in a lot of operations on each keypress.
- No need to set this.nodeProperties.nodeBetriebspunktName nor this.nodeProperties.nodeBetriebspunktFullName on keyup: this is already done automatically by [ngModel].
Note that we do loose a bit of functionality with this patch: the diagrams and sidebar headings aren't updated in real-time as the user types anymore. If this is deemed important functionality, we could use `(ngModelChange)` instead.
=> fix: use change event instead of keyup for node name change

src/app/view/editor-menu/editor-menu.component.scss
=> The menubar has a visual "thick" separator in between variant/project name and the filter symbol is resolved

documentation/CREATE_TRAINRUN.md
- new**ly** created ...
- such **as** ...
- **it** gets ...
- For **more** details ...
- has to **be** manually ...
- al**ign**ment ...
spelling, grammar
=> fix: doc: CREATE_TRAINRUN.md, spelling, grammar

documentation/DATA_MODEL_JSON.md
- ... labe**ls** ...
- Arr**ay** of integer
spelling
=> fix: doc: DATA_MODEL_JSON.md, spelling

documentation/DATA_MODEL_JSON.md, src/app/data-structures/business.data.structures.ts, src/app/sample-netzgrafik/netzgrafik.default.ts, src/app/utils/data-migration.ts, src/app/view/editor-tools-view-component/editor-tools-view.component.ts, src/integration-testing/netzgrafik.unit.test.reconnec.trainrunsectionst.ts, src/integration-testing/netzgrafik.unit.testing.od.matrix.ts, src/integration-testing/netzgrafik.unit.testing.transition.ts, src/integration-testing/netzgrafik.unit.testing.ts
migrate originDestination connectionPenalty to netzgrafikDto
https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/issues/199
=> feat: migrate originDestination connectionPenalty to netzgrafikDto

documentation/ORIGIN_DESTINATION_MATRIX.md, src/app/view/editor-tools-view-component/editor-tools-view.component.ts, src/app/view/util/origin-destination-graph.ts, src/integration-testing/origin.destination.csv.test.spec.ts
Optimize "medium" CSV computing from 2s to approx. 0.5s on my machine (while increasing the schedule duration from 10 hours to 16 hours).
close https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/issues/270
=> feat: optimize originDestination graph

src/app/services/data/trainrun.service.spec.ts, src/app/services/data/trainrun.service.ts, src/app/view/editor-tools-view-component/editor-tools-view.component.ts, src/app/view/util/origin-destination-graph.ts, src/integration-testing/netzgrafik.unit.testing.od.matrix.ts, src/integration-testing/origin.destination.csv.test.spec.ts
fix O/D Matrix for unordered trainruns
close https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/issues/312
=> fix: fix O/D Matrix for unordered trainruns

documentation/CREATE_TRAINRUN.md, documentation/USERMANUAL.md, documentation/technical/trainrun_iterations.md, src/app/perlenkette/model/perlenkette-tests.spec.ts, src/app/perlenkette/model/perlenketteNode.ts, src/app/perlenkette/model/perlenketteSection.ts, src/app/perlenkette/perlenkette.component.html, src/app/perlenkette/perlenkette.component.ts, src/app/perlenkette/service/load-perlenkette.service.ts, src/app/services/data/trainrun.service.ts, src/app/services/util/trainrunsection.helper.ts, src/app/streckengrafik/services/sg-1-load-trainrun-item.service.ts, src/app/view/util/generalViewFunctions.ts
This change fixes the problem if a trainrun does not have a continuous path from the start to the destination, i.e. if sections are missing in the path that should continuously connect the nodes from the start to the end. These **holes** are artifacts that can occur during drawing if the train has not been drawn correctly or has not yet been fully drawn. So there can always be a train run that has "holes" along the path, i.e. missing train run sections along the path, e.g.
A - B - C ---- missing --- E - F - G --> also no section between C and E.
The solution to the problem - described above - is proposed in this fix: The trainrun has two parts: [(A B), (A C)] and [(E F)(F G)]. The trainrun is now interpreted as two separate train runs. The network diagram provides no information as to …
=> fix: 320 bug graphical timetable streckengrafik renders only one trainrun segement

src/app/services/data/trainrun.service.ts
While combining two trainruns the first trainrun will "survive" and the second one will be deleted. If the trainrun which will be deleted consists of more than one trainrun segment (connected paths) the reported issue will be generated.
https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/issues/330
=> fix: Combining train journeys that consist of more than one trainrun segment has been fixed.

documentation/DATA_MODEL_JSON.md, src/app/view/editor-tools-view-component/editor-tools-view.component.ts
The import of JSON from third-party providers has been simplified - or allowed. If no node has a port or if all ports are empty or no TrainrunSection has a path, then the import should be adjusted so that all nodes are created and then each train is inserted section by section. This makes the import (exchange) from 3rd party more easy.
=> fix: Simplified third-party JSON import (no port alignment/path precalculation required)

src/app/services/data/trainrunsection.service.ts
When deleting multiple nodes or trainrun sections, it's crucial that the delete loop doesn't refresh the rendering for each deleted element. The deletions should be performed all at once at the end - only one update (refresh) should be triggered. This is now implemented and improves the performance.
https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/issues/350
=> fix: 350 bug delete node or trainrunsections cause low performance

src/app/app.component.html, src/app/app.component.ts, src/app/core/i18n/i18n.module.ts, src/app/core/i18n/i18n.service.ts, src/app/core/i18n/translate.pipe.ts
- Initialize application language with navigator language if no preference (= first connection) in localStorage
- Allow to change language from the application without window reload
- Allow to change language from the outer of the application with `@Input (setter)` (in `standalone` mode especially)
- I renamed `"locale" -> "language"` since a locale is something like `"fr-FR"` and a language `"fr"`, and we use `"fr"` as value for the language ; but i can revert these changes and bring back the `"locale"`
- Cannot use `@Input (getter)` to uniformize the code, because the getter is called at any change (including mouse move), then involving too many actions and crash the application
- (Edit: removed) Could we also remove this button ? @aiAdrian  or is it still used for demo purpose on your …
=> Refacto language + add navigator preferences

src/app/models/trainrunsection.model.ts, src/app/services/util/trainrunsection.validator.ts, src/app/services/util/transition.validator.spec.ts, src/app/view/editor-main-view/data-views/trainrunsections.view.ts, src/app/view/editor-tools-view-component/editor-tools-view.component.ts, src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/fr.json, src/assets/i18n/it.json
Add warning for unsymmetric times. Those times can be imported when importing Netzgrafik from 3rd parties
Previously, the system did not warn users about the presence of unsymmetric times. This commit adds functionality to detect and alert users when unsymmetric times exists.
2nd part of the fix is that the user will have a tooltip (svg:titel) show warning message when hovering over the element.
=> fix: warn users when having unsymmetric times

src/app/view/editor-menu/editor-menu.component.html
As this box is always "read-only", we can just remove it, to make the UI clearer
From:
To:
=> fix: remove variante read/write button from standalone env

documentation/ORIGIN_DESTINATION_MATRIX.md, src/app/view/editor-tools-view-component/editor-tools-view.component.ts, src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/fr.json, src/assets/i18n/it.json
=> fix: correct connections->transfers naming for O/D matrix

documentation/USERMANUAL.md
- disabl**ed** eye
- For mo**re** details...
- modi**fy**
- indep**ende**nt
- **a** user-friendly
- (... hour)**, and** time category (...)
=> docs: fix spelling in USERMANUAL.md

README.md
Add link to one-stop-shop Docker Compose based demo.
=> Add link to one-stop-shop Docker Compose based demo.

.gitignore, README.md, flake.lock, flake.nix
nix package manager users can setup a shell environnement based on a flake.nix file that describes tools and versions needed to dev and run the project, this flake contains:
- nodejs 20
- npm
- typescript language server
- angular language service
nix flakes combinated with direnv allow to open a project folder with automatic setup launch, creates en .envrc file and a .direnv directory. -> not every contributors use it and want to have those dotfiles, so it should be ignored by git.
=> setup: add nix flake

src/app/app.component.ts, src/app/netzgrafik-application/netzgrafik-application.component.ts
In standalone mode, the DTO might be passed as an HTML element custom attribute. The attribute can be set before NGE is inserted into the DOM like so:
const sbbRoot = document.createElement('sbb-root');
sbbRoot.netzgrafikDto = dto;
document.body.appendChild(sbbRoot);
However, when using the custom attribute this way, the DTO gets overwritten with the default DTO when NetzgrafikApplicationComponent initializes.
Fix this by loading the DTO in AppComponent.ngOnInit instead, only if the user hasn't set the netzgrafikDto custom attribute.
This allows users to set an initial DTO before NGE starts up. Previously, users had to set the DTO after inserting NGE into the DOM and this caused a visible glitch: the default DTO was visible for a split second before the user-provided DTO got loaded.
=> Don't overwrite initial DTO in standalone mode

documentation/DATA_MODEL_JSON.md, src/app/view/editor-main-view/data-views/trainrunsections.view.ts, src/app/view/editor-main-view/data-views/transitions.view.ts
Issue reported by @louisgreiner 
Sarah and Yohan made a discovery about how the train run sections are rendered: for the same section, 4 HTML objects are always rendered (with the same ID, which is surprising for HTML). There is no difference between the 4 objects, except that one of them has a different opacity. Is this normal, or does it serve a special purpose? If not, could it be a potential area for performance improvement to render only one object?
=> fix: Performance - only render trainrunSection and transition element - which are required

src/app/origin-destination/components/origin-destination.component.ts
With that change, the origin and destination nodes are bold when the mouse is over a cell.
I am not sure on:
- the relevance of this enhancement
- if relevant, the font-size chosen : 12px or less/more?
- if relevant, we could also change the color of the text, or anything else that make the nodes names highlit
What do you think @aiAdrian ?
=> od: make od nodes bold on mouseover

documentation/ORIGIN_DESTINATION_MATRIX.md, src/app/app.module.ts, src/app/services/analytics/origin-destination/components/origin-destination.component.html, src/app/services/analytics/origin-destination/components/origin-destination.component.scss, src/app/services/analytics/origin-destination/components/origin-destination.component.ts, src/app/services/analytics/origin-destination/components/origin-destination.service.ts, src/app/services/data/origin-destination.service.ts, src/app/services/ui/level.of.detail.service.ts, src/app/services/ui/ui.interaction.service.ts, src/app/view/editor-main-view/data-views/editor.view.ts, src/app/view/editor-menu/editor-menu.component.html, src/app/view/editor-menu/editor-menu.component.scss, src/app/view/editor-menu/editor-menu.component.ts, src/app/view/editor-menu/editor-mode.ts, src/app/view/editor-tools-view-component/editor-tools-view.component.html, src/app/view/editor-tools-view-component/editor-tools-view.component.ts, src/app/view/filter-main-side-view/filter-main-side-view.component.html, src/app/view/filter-main-side-view/filter-main-side-view.component.ts, src/app/view/filter-main-side-view/main-view-mode.ts, src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/fr.json, src/assets/i18n/it.json
https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/issues/404
=> Display matrices O/D

documentation/AdvancedEditingShortcuts.md, src/app/view/editor-main-view/data-views/editor.view.ts, src/app/view/editor-main-view/editor-main-view.component.ts, src/app/view/util/svg.mouse.controller.ts
Closes https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/issues/464
The above issue is a known issue : https://stackoverflow.com/questions/5527601/normalizing-mousewheel-speed-across-browsers
`d3.event.ctrlKey` is not detect when track pad is used. The solution is to get this event through an event listener.
* [ x I've read the [Contribution Guidelines](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/CONTRIBUTING.md)
=> scale-netzgrafik: fix touchpad gesture with ctrl event listener

src/app/view/dialogs/trainrun-and-section-dialog/trainrunsection-tab/trainrun-section-tab.component.ts
The current timeout before focusing an element is too long, and the user might think the app is laggy. 100ms is ok
The perlenkette already uses 100ms timeout
=> ux: reduce timeout when focus an element on a trainrun section

src/app/view/editor-main-view/data-views/trainrunsections.view.edgeline.scss, src/app/view/editor-main-view/data-views/transition.view.scss
When the user is moving the mouse pointer over a trainrun section, the trainrun sections stroke-width gets wider.
=> fix: Highlight entire trainrun when hovering a trainrun section line

src/app/streckengrafik/components/streckengrafik.component.html, src/app/view/editor-tools-view-component/editor-tools-view.component.ts
I located the problem. It's the classic CSS style loss problem with saveSvgAsPng when exporting, especially if your SVG relies on external stylesheets or scoped component styles. The root cause: saveSvgAsPng only serializes inline styles by default, so anything coming from external CSS or Angular’s component encapsulation can get dropped.
This approach helps preserve visual fidelity, especially for dynamic styles such as media queries, fonts, and layout-specific rules.
This solution is still **in progress**. While it improves style retention, performance is currently **very poor** esspecially for Graphical Timetable — the inlining process takes too long for large or complex SVGs. Further optimization is needed before it can be used in production.
- Netzgrafik export : ok.
- O/D Matrix …
=> 470 bug export features bugged png svg
