src/app/streckengrafik/services/sg-6-track.service.ts
=> fixed cause crashed

documentation/USERMANUAL.md, src/app/perlenkette/perlenkette.component.html, src/app/perlenkette/perlenkette.component.ts
=> feature implemened

.github/workflows/preview-image-cleanup.yml
Fix the typo in `PACKAGE_NAME` for the image cleanup job
=> ci: fix PACKAGE_NAME for preview image cleanup job

.github/workflows/continuous-integration-secure.yml
FIx the duplicate ID in the secure CI job.
=> ci: remove duplicate id in secure CI job

.github/workflows/release-please.yml
Use Docker GitHub Actions in release-please job
=> ci: use Docker actions in release-please job

src/app/view/editor-tools-view-component/editor-tools-view.component.ts
There was an error in the export of the trainrun total turnaround times due to a specific issue, resulting in incorrect data being generated through the trainruns. The problem was located and fixed
=> 109 bug export trainrun circulation information at destination is broken

src/app/streckengrafik/services/sg-6-track.service.ts, src/app/streckengrafik/services/streckengrafik.services.spec.ts
=> broken test fixed

ROADMAP.md
=> Workshop sncf roadmap

src/app/streckengrafik/components/streckengrafik.component.scss, src/app/view/filter-main-side-view/filter-main-side-view.component.scss
Streckengrafik (graphical timetable) 's background color of "root component" was wrongly set to whitesmoke. 
Non functional fix, just UI looks more beautiful
=> coloring issue fixed

src/app/services/data/trainrun.service.ts, src/app/streckengrafik/services/sg-1-load-trainrun-item.service.ts, src/app/streckengrafik/services/streckengrafik.services.spec.ts, src/app/utils/multi-select-node-graph.ts, src/app/view/editor-menu/editor-menu.component.html, src/app/view/editor-menu/editor-menu.component.ts
The feature https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/issues/132 is initially implemented.
=> initial changes to enable the new feature

src/app/services/ui/ui.interaction.service.ts, src/app/streckengrafik/services/sg-1-load-trainrun-item.service.ts, src/app/view/editor-menu/editor-menu.component.ts
=> refactored

src/app/streckengrafik/services/sg-1-load-trainrun-item.service.ts, src/app/utils/multi-select-node-graph.ts
=> 136 bug path finding for user defined corridor takes too long for big scenarios

src/app/services/ui/ui.interaction.service.ts, src/app/streckengrafik/services/sg-1-load-trainrun-item.service.ts, src/app/view/editor-menu/editor-menu.component.ts
=> refactored code and cleaned up

package-lock.json
`npm install` fails under macOS. Add required optional `nx` dependencies to `package-lock.json`.
=> Fix npm install for macOS.

src/app/streckengrafik/services/sg-1-load-trainrun-item.service.ts, src/app/utils/multi-select-node-graph.ts
=> 140 feature enhancement mean travel time must be use for scaling

src/app/perlenkette/service/load-perlenkette.service.ts, src/app/services/data/copy.service.spec.ts, src/app/services/data/netzgrafikColoring.service.spec.ts, src/app/services/ui/ui.interaction.service.spec.ts, src/app/streckengrafik/services/streckengrafik.services.spec.ts, src/app/view/editor-main-view/data-views/connections.view.spec.ts, src/app/view/editor-main-view/data-views/d3.utils.spec.ts, src/app/view/editor-main-view/data-views/data.view.spec.ts, src/app/view/editor-main-view/data-views/nodes.view.spec.ts, src/app/view/editor-main-view/data-views/notes.view.spec.ts, src/app/view/editor-main-view/data-views/trainrunsections.view.spec.ts, src/app/view/editor-main-view/data-views/transitions.view.spec.ts
=> filtering issue fixed

src/app/view/editor-tools-view-component/editor-tools-view.component.ts
=> reported bug fixed

src/app/netzgrafik-application/netzgrafik-application.component.ts, src/app/services/ui/ui.interaction.service.ts, src/app/view/editor-main-view/data-views/editor.view.ts
=> 148 bug load new netzgrafik can lead to an empty screen due of mal placement of the view center

src/app/models/node.model.ts, src/app/models/trainrunsection.model.spec.ts, src/app/models/trainrunsection.model.ts, src/app/services/data/trainrun.service.spec.ts, src/app/services/data/trainrun.service.ts
The issue has been fixed. 
**Case 1:** 
Before 
After combine - time gets not changed due of 60min
**Case 2:**
Before 
After combine - the departure time is in next hour, but by merging the trainrun passes in the same hours ( odd => enforces odd, even enforces even) - special case 120 freq.
**Case 3**
Before
After 
**Case 4**
Before
After combine: Departure and arrival time => equal => non stop flag set (54 = 24 + 30 (freq))
**Case  5**
Before 
After 
**Case 6**
Before 
After
=> Problem fixed

docker/nginx-angular.conf
Fix location expression in nginx configuration (the current location never matches css/js files). Set  ttl for js/css to 1y as intended.
=> Set ttl for js/css to 1y instead, fix location expression.

.github/workflows/continuous-integration.yml
Fix duplicate trigger when pushing to a branch in an open PR.
=> ci: fix duplicate trigger when pushing to a PR

angular.json
=> fix: enable output hashing by default

src/app/view/editor-main-view/data-views/trainrunsection.previewline.view.ts
The issue with the rendering of the Trainrun section when undocking/docking gets fixed throught this PR. This was not a functional issue, only a cosmetic one.
=> TrainrunSection undock/dock without changing

src/app/view/dialogs/trainrun-and-section-dialog/trainrunsection-tab/trainrun-section-tab.component.scss
=> Background coloring issue fixed

angular.json
=> Fix local dev environment.

package-lock.json, package.json
This PR only updates the version information in the package.json and package_lock.json - merge and then we have to add a tag: 
git tag v2.7.0 
git push --tags 
=> Release not have to be updated
=> Preparation Version 2.7.0 (Release)

src/app/models/trainrunsection.model.ts
Use a loop instead of repeating the replace() calls.
=> refactor: simplify formatDisplayText()

src/app/perlenkette/perlenkette-section/perlenkette-section.component.html, src/app/view/editor-properties-view-component/editor-properties-view.component.html, src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/fr.json, src/assets/i18n/it.json
Missing translation from previous translation work
=> Missing translations

src/app/view/dialogs/note-dialog/note-dialog.component.html, src/app/view/dialogs/note-dialog/note-dialog.component.ts, src/app/view/editor-edit-tools-view-component/editor-edit-tools-view.component.html, src/app/view/editor-edit-tools-view-component/editor-edit-tools-view.component.ts, src/app/view/editor-filter-view/editor-filter-view.component.html, src/app/view/editor-filter-view/editor-filter-view.component.ts
Notes are disabled in standalone mode.
=> fix: disable notes in filter sidebar in standalone mode

.github/workflows/release-please.yml
=> Updated release-please.yml

.github/workflows/release.yml, README.md
=> Fix tag patterns complying with extended tags from release-please.

documentation/AdvancedEditingShortcuts.md
- ... system **saves** it ...
- ... Use the **copy-paste** idea: Select the train **and** press ...
fix grammar and spelling
=> Update AdvancedEditingShortcuts.md, grammar, spelling

src/app/view/variant/variants-view/variants-view.component.html
**Before the fix  the netzgrafik-editor shows:**
test app.view.variant.variants-view.archived
**After the fix the netzgrafik-editor shows:** 
test (archived)
<h1>
{{ proj.name }}
<ng-container *ngIf="proj.isArchived">{{ ' ' + 'app.view.variant.variants-view.archived' | translate }}</ng-container>
</h1>
string concat doesn't work within html and transle
=> The translation bug is fixed

documentation/CREATE_FILTERS.md
- invisible
- visible
fix spelling
=> fix: doc: Update CREATE_FILTERS.md, spelling

documentation/CREATE_NODES.md
- semicolon-**separate**-value
- comma separated **filter**able labels
- a**lign**ment, a**lign**ed
spelling issues
=> fix: doc: CREATE_NODES.md, spelling

src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/fr.json, src/assets/i18n/it.json
- F**ar**be
- F**ar**bschema
- New fi**lt**er
- ...
Found some spelling issues in
https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/src/assets/i18n/de.json
and
https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/src/assets/i18n/en.json
> "ui": {
>         "newFilter": "New filer"
>       },
=> fix: Update de.json, en.jason, spelling

src/app/netzgrafik-application/netzgrafik-application.component.html, src/app/netzgrafik-application/netzgrafik-application.component.scss, src/app/netzgrafik-application/netzgrafik-application.component.ts
Replaced hard coded styling with css one (much better)
=> fix: Technical - replace hard coded style with common browser css styling <sbb-icon-sidebar-container>

documentation/Graphic_Timetable.md
- **al**ong
- **an ea**rly phase
- the diagram ... reveal**s** ...
- sep**arate**ly
- mi**ni**mum
- i.e**.,**
https://www.merriam-webster.com/dictionary/separately
=> fix: doc: Graphic_Timetable.md, spelling, grammar, punctuation

documentation/ORIGIN_DESTINATION_MATRIX.md, src/app/services/data/node.service.ts, src/app/view/editor-tools-view-component/editor-tools-view.component.html, src/app/view/editor-tools-view-component/editor-tools-view.component.ts, src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/fr.json, src/assets/i18n/it.json
add the interface for origin-destination CSV
close https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/issues/268
I could use help for:
- What kind of tests would you like?
- What kind of documentation would you like?
- Should we hide the button while the feature is WIP?
- Is this 5-column format OK, rather than 3 matrices?
- What should be the German translations?
- I tried prettier but it seems the current code is not compliant.
=> add the interface for origin-destination CSV

documentation/STANDALONE.md, src/app/app.component.ts, src/app/models/operation.model.ts, src/app/services/data/label.serivce.ts
This PR allows you to add the operation update to labels.
=> Add label operation

documentation/STANDALONE.md
- Operations can be simply ignored
=> fix: doc: STANDALONE.md grammar

documentation/Split_Combine_Trainruns.md
-  ... must be **held** pressed as long **as** you ...
grammar
https://www.merriam-webster.com/dictionary/hold#examples
https://www.merriam-webster.com/dictionary/as%20long%20as
=> fix: doc: Split_Combine_Trainruns.md grammar

documentation/USERMANUAL.md
- **consists of** one or more ...
- **e.g.,** ...
- For **more** details ...
- allows **you** to edit ...
- propa**ga**tion
- switch**es** ...
- **vice**-versa
- Vi**si**ble eye ...
https://www.merriam-webster.com/dictionary/consist%20of
https://www.merriam-webster.com/dictionary/e.g.#examples
https://www.merriam-webster.com/sentences/switch#exemplar-entry-2
=> fix: doc: USERMANUAL.md spelling grammar punctuation

index.html
=> git-hub-pages-deployement-fix

documentation/DATA_MODEL_JSON.md
> Documentation enhanced 
> standalone application deployed to github pages [https://schweizerischebundesbahnen.github.io/netzgrafik-editor-frontend/](https://schweizerischebundesbahnen.github.io/netzgrafik-editor-frontend/)
=> fix: Documentation enhanced and standalone application deployed to github pages

.github/workflows/continuous-integration.yml
=> fix: Update continuous-integration.yml

src/integration-testing/node.service.test.spec.ts
Improves on https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/pull/280
=> test: improve NodeService coverage

documentation/ORIGIN_DESTINATION_MATRIX.md, src/app/services/data/trainrun.service.ts, src/app/view/editor-tools-view-component/editor-tools-view.component.html, src/app/view/editor-tools-view-component/editor-tools-view.component.ts, src/app/view/util/origin-destination-graph.ts, src/integration-testing/netzgrafik.unit.testing.od.matrix.ts, src/integration-testing/origin.destination.csv.test.spec.ts
(I'll fix the commit message after reviews.)
This is the first useful version of this feature. There is still some room for optimization, but it seems quite fast so far (2s for the medium example). Note that some trainruns don't have any endNode on this example.
close https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/issues/269
=> feat: Implement Origin/Destination matrix

src/app/services/data/trainrun.service.spec.ts
improve TrainrunService coverage
https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/issues/199
=> test: improve TrainrunService coverage

src/app/view/util/origin-destination-graph.ts, src/integration-testing/netzgrafik.unit.testing.od.matrix.ts, src/integration-testing/origin.destination.csv.test.spec.ts
style: format O/D Matrix source using prettier
https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/issues/199
=> style: format O/D Matrix source using prettier

documentation/DATA_MODEL.md
This chapter can be moved to a separate chapter later if required.
Documentation enhanced
=> Update the datamodel with information about trainrun iteration

src/app/view/util/origin-destination-graph.ts
fix O/D Matrix for trainrun 0
close https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/issues/199
=> fix: fix O/D Matrix for trainrun 0

documentation/DATA_MODEL_JSON.md, src/app/view/editor-tools-view-component/editor-tools-view.component.ts
The base data export was broken. Two fields where missing: 
- region
- IPV
=> fix: CSV base data export 

src/app/view/editor-tools-view-component/editor-tools-view.component.ts, src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/fr.json, src/assets/i18n/it.json
=> fix: 346 bug importing 3rd party json misses detecting non stop transitions

src/app/services/data/node.service.ts, src/app/view/editor-main-view/data-views/editor.keyEvents.ts
=> fix: performance issue fixed (part 2)

src/app/view/editor-main-view/data-views/editor.keyEvents.ts
=> fix: performance opt / refactored

src/app/perlenkette/service/load-perlenkette.service.ts
=> fix: build broken!

src/app/services/data/data.service.ts, src/app/services/data/trainrunsection.service.ts, src/app/view/editor-tools-view-component/editor-tools-view.component.ts
=> fix: import 3rd party performance

src/assets/i18n/de.json
=> fix: Translation - de.json - "tag" - typo fixed

src/app/view/editor-main-view/data-views/editor.view.ts
=> fix: multi-nodes scaling ctrl + mouse wheel

src/app/app.component.ts, src/app/services/util/position.transformation.service.ts
Missing operation emitters for the position transformation feature (align with up/down/right/left)
=> fix: emit operations for position transformation service

src/app/services/data/trainrun-section-times.service.ts, src/app/services/util/trainrunsection.helper.ts
add checkAndAdjustSymmetry() in trainrunsection.helper.ts
=> trainrun: isolate symmetry check

package.json
For development purpose only, to ease the lint and lint fixing issues
=> config: add lint:fix command

src/app/data-structures/business.data.structures.ts, src/app/models/trainrun.model.ts, src/app/models/trainrunsection.model.ts, src/app/sample-netzgrafik/netzgrafik.default.ts, src/app/services/data/trainrun-section-times.service.ts, src/app/services/data/trainrun.service.ts, src/app/services/data/trainrunsection.service.ts, src/app/services/util/trainrunsection.helper.ts, src/app/view/dialogs/trainrun-and-section-dialog/trainrun-tab/trainrun-tab.component.html, src/app/view/dialogs/trainrun-and-section-dialog/trainrun-tab/trainrun-tab.component.ts, src/app/view/dialogs/trainrun-and-section-dialog/trainrunsection-tab/trainrun-section-tab.component.html, src/app/view/dialogs/trainrun-and-section-dialog/trainrunsection-tab/trainrun-section-tab.component.ts
- move isSymmetric from TrainrunDto to trainrunServiceDto
- adapt related services and helpers
- in trainrunSection html template, display isSymmetric checkbox only if isRoundTrip is true
=> symmetry: move symmetry to trainrunSection

src/app/models/trainrunsection.model.ts, src/app/perlenkette/perlenkette-section/perlenkette-section.component.html, src/app/perlenkette/perlenkette-section/perlenkette-section.component.ts, src/app/services/data/node.service.ts, src/app/services/data/trainrun-section-times.service.ts, src/app/services/data/trainrunsection.service.ts, src/app/services/util/trainrunsection.validator.ts, src/app/view/editor-tools-view-component/editor-tools-view.component.ts
This PR should clean some part of the code that I am passing by
=> [WIP] Fix multiple typos

src/app/services/ui/filter.service.ts, src/app/view/editor-main-view/data-views/connections.view.ts, src/app/view/editor-main-view/data-views/nodes.view.ts, src/app/view/editor-main-view/data-views/trainrunsections.view.ts, src/app/view/editor-main-view/data-views/transitions.view.ts
=> fix: The performance gets improved for big Netzgrafik

src/app/app.component.ts, src/app/services/ui/ui.interaction.service.ts, src/app/view/dialogs/trainrun-and-section-dialog/trainrun-and-section-dialog.component.ts, src/app/view/editor-tools-view-component/editor-tools-view.component.ts
Close https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/issues/433
=> fix: reset main view after netzgrafikDto import

src/app/origin-destination/components/origin-destination.component.ts, src/app/services/data/origin-destination.service.ts, src/app/view/editor-main-view/data-views/editor.view.ts
origin-destination: allow node selection and trainrun filtering
selecting nodes
filtering trainruns
https://github.com/OpenRailAssociation/osrd/issues/11493
=> feat: origin-destination: allow node selection and trainrun filtering

src/app/view/editor-main-view/data-views/trainrunsection.previewline.view.ts
=> fix: Move trainrun when filter temp. switched off (not toggling)

src/app/origin-destination/components/origin-destination.component.scss, src/app/origin-destination/components/origin-destination.component.ts
Close https://github.com/OpenRailAssociation/osrd/issues/11491
=> od: center od matrix

src/app/origin-destination/components/origin-destination.component.ts, src/app/view/editor-menu/editor-menu.component.ts
bug: fix zoom value when switching view
=> bug: fix zoom value when switching view

src/app/data-structures/business.data.structures.ts, src/app/models/filterSettings.model.ts, src/app/sample-netzgrafik/Demo_Netzgrafik_Fernverkehr_2024.json, src/app/services/ui/filter.service.ts, src/app/view/editor-filter-view/editor-filter-view.component.html, src/app/view/editor-filter-view/editor-filter-view.component.ts, src/app/view/editor-main-view/data-views/editor.view.ts, src/app/view/editor-main-view/data-views/trainrunSectionViewObject.ts, src/app/view/editor-main-view/data-views/trainrunsections.view.ts, src/app/view/editor-main-view/editor-main-view.component.ts, src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/fr.json, src/assets/i18n/it.json
=> one-way: add trainrun direction arrows filter

src/app/models/trainrunsection.model.ts, src/app/services/data/trainrunsection.service.ts, src/app/streckengrafik/components/train-run-node/trainrun-node.component.ts, src/app/streckengrafik/model/pathItem.ts, src/app/streckengrafik/model/pathNode.ts, src/app/streckengrafik/model/pathSection.ts, src/app/streckengrafik/model/streckengrafik-model/sg-selected-trainrun.ts, src/app/streckengrafik/model/streckengrafik-model/sg-trainrun-item.ts, src/app/streckengrafik/model/streckengrafik-model/sg-trainrun-node.ts, src/app/streckengrafik/model/streckengrafik-model/sg-trainrun-section.ts, src/app/streckengrafik/model/streckengrafik-model/sg-trainrun.ts, src/app/streckengrafik/model/trainrunItem.ts, src/app/streckengrafik/services/sg-1-load-trainrun-item.service.ts, src/app/streckengrafik/services/sg-2-trainrun-path.service.ts, src/app/streckengrafik/services/sg-3-trainruns.service.ts, src/app/streckengrafik/services/sg-6-track.service.ts, src/app/streckengrafik/services/streckengrafik.services.spec.ts, src/app/view/editor-main-view/data-views/trainrunsections.view.ts
The _streckengrafik_ has been adapted to correctly display oneway trainruns
=> oneway: adapt streckengrafik for one way trainrun

LICENSE
Add full Apache 2.0 license text, as requested in https://github.com/OpenRailAssociation/technical-committee/issues/120#issuecomment-2912069072
n/a
=> chore: add full Apache 2.0 license text

src/app/app.component.html
https://github.com/OpenRailAssociation/netzgrafik-editor-frontend/blob/main/documentation/USERMANUAL.md
=> fix: Link to the user manual - new location

src/app/sample-netzgrafik/netzgrafik.demo.standalone.github.ts
=> fix: wrong data in JSON -> labelIds are outdated

src/app/data-structures/business.data.structures.ts, src/app/models/node.model.ts
-Node: add isCollapsed attribut and associated getter setter
#536 
The removing parts will be handle at the end of the node management system development to ensure that nothing is left behind.
=> models: node: add isCollapsed attribut

src/app/streckengrafik/components/slider/time-slider/time-slider.component.scss, src/app/streckengrafik/components/slider/time-slider/time-slider.component.ts
=> fix: Firefox rendering issue fixed – styling slightly changed
